version: "3.5"

services:
 plagiarism-platform-backend:
  container_name: plagiarism-platform-backend
  # image: gabrielsoaresdev/projectdefaultadonis:latest
  restart: always
  ports:
   - "3335:3335"
  networks:
   - proxy-reverse-network
   - plagiarism-platform-network
  env_file:
     - stack.env
networks:
  plagiarism-platform-network:
   name: plagiarism-platform-network
   external: true
  proxy-reverse-network:
   name: proxy-reverse-network
   external: true


