version: "3.5"

services:
 plagiarism-platform-backend:
  container_name: plagiarism-platform-backend
  image: gabrielsoaresdev/plagiarism-back:latest
  restart: always
  ports:
   - "3335:3335"
  networks:
   - proxy-reverse-network
   - plagiarism-platform-network
   - postgres-network
  env_file:
     - env-production
networks:
  plagiarism-platform-network:
   name: plagiarism-platform-network
   external: true
  proxy-reverse-network:
   name: proxy-reverse-network
   external: true
  postgres-network:
    name: postgres-network
    external: true



