version: "3.5"

services:
 default-project-adonis:
  container_name: default-project-adonis
  image: gabrielsoaresdev/projectdefaultadonis:latest
  restart: always
  volumes:
   - node_modules-default-project-adonis:/app/default-project-adonis/node_modules
  ports:
   - "3333:3333"
  networks:
   - mysql-network
   - proxy-reverse-network
   - default-project-adonis-network

volumes:
  node_modules-default-project-adonis:
   name: node_modules-default-project-adonis
networks:
  default-project-adonis-network:
   name: default-project-adonis-network
   driver: bridge
  mysql-network:
   name: mysql-network
   external: true

  proxy-reverse-network:
   name: proxy-reverse-network
   external: true


